# Dockerfile.dev — Development (hot reload)
FROM node:20-alpine

WORKDIR '/app'
COPY package*.json ./
RUN npm install

RUN npm install -D typescript ts-node nodemon

COPY tsconfig.json ./

ENV NODE_ENV=development \
    PORT=5560

EXPOSE 5560
CMD ["npm", "run", "dev"]
